# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

# Train settings -------------------------------------------------------------------------------------------------------
epochs: 100 # (int) number of epochs to train for
batch: 16 # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640 # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
max_len: 100
device: 0 # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 3 # (int) number of worker threads for data loading (per RANK if DDP)
project: runs # (str, optional) project name
name: train
optimizer: Adam # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]e
resume: False # (bool) resume training from last checkpoint
amp: False
freeze: [ 'encoder' ]  # (str | list, optional) freeze name layers, or freeze list of layer name during training


# Hyperparameters ------------------------------------------------------------------------------------------------------
lre0: 0.003 # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrd0: 0.003 # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.1 # (float) final learning rate (lr0 * lrf)
momentum: 0.9 # (float) SGD momentum/Adam beta1 (i.e. SGD=0.937, Adam=0.9)
weight_decay: 0.0005 # (float) optimizer weight decay 5e-4
nbs: 64 # (int) nominal batch size